name: wh_covid19
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ^2.8.0-dev
  flutter: ^1.15.17

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.0+16
  chewie: ^0.9.10
  video_player: ^0.10.8+1
  flutter_widget_from_html: ^0.3.2+2
  matrix_gesture_detector: ^0.1.0
  url_launcher: ^5.4.2
  flutter_svg: ^0.17.3+1
  shared_preferences: ^0.5.6+3
  intl: ^0.16.0
  photo_view: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icon/
    - assets/images/icon/SVG/
    - assets/images/steps/
    - assets/text/
    - assets/videos/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-300-Light.ttf
          weight: 300

        - asset: assets/fonts/Inter-400-Regular.ttf
          weight: 400

        - asset: assets/fonts/Inter-500-Medium.ttf
          weight: 500

        - asset: assets/fonts/Inter-600-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Inter-700-Bold.ttf
          weight: 700
